
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posts_evaluator_development

test:
  <<: *default
  database: posts_evaluator_test


production:
  <<: *default
  database: posts_evaluator_production

